/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.form;

import client.Session;
import dbb.Util;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import server.form.modeli.ModelTblKlijenti;
import server.thread.ThreadServer;

/**
 *
 * @author alekd_000
 */
public class FrmServer extends javax.swing.JFrame {

    Thread clock;
    Thread server;  
    
    /**
     * Creates new form FrmServer
     */
    public FrmServer() {
        initComponents();
        btnZaustaviServer.setEnabled(false);
        btnIzbaciKlijenta.setEnabled(false);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSveKomponente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnPokreniServer = new javax.swing.JButton();
        btnZaustaviServer = new javax.swing.JButton();
        btnIzbaciKlijenta = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        panelTblKlijenti = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        panelSveKomponente.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametri konekcije na bazu"));

        jLabel1.setText("URL");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        btnPokreniServer.setText("POKRENI SERVER");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        btnZaustaviServer.setText("ZAUSTAVI SERVER");
        btnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviServerActionPerformed(evt);
            }
        });

        btnIzbaciKlijenta.setText("Izbaci klijenta");
        btnIzbaciKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciKlijentaActionPerformed(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        javax.swing.GroupLayout panelTblKlijentiLayout = new javax.swing.GroupLayout(panelTblKlijenti);
        panelTblKlijenti.setLayout(panelTblKlijentiLayout);
        panelTblKlijentiLayout.setHorizontalGroup(
            panelTblKlijentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTblKlijentiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTblKlijentiLayout.setVerticalGroup(
            panelTblKlijentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTblKlijentiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSveKomponenteLayout = new javax.swing.GroupLayout(panelSveKomponente);
        panelSveKomponente.setLayout(panelSveKomponenteLayout);
        panelSveKomponenteLayout.setHorizontalGroup(
            panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSveKomponenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSveKomponenteLayout.createSequentialGroup()
                        .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelSveKomponenteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSveKomponenteLayout.createSequentialGroup()
                                .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword))
                        .addGap(56, 56, 56)
                        .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnZaustaviServer, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnPokreniServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelTblKlijenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSveKomponenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzbaciKlijenta)
                .addGap(18, 18, 18))
        );
        panelSveKomponenteLayout.setVerticalGroup(
            panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSveKomponenteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSveKomponenteLayout.createSequentialGroup()
                        .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSveKomponenteLayout.createSequentialGroup()
                        .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelSveKomponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(panelTblKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIzbaciKlijenta)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSveKomponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSveKomponente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzbaciKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciKlijentaActionPerformed
        ModelTblKlijenti mtk = (ModelTblKlijenti) tblKlijenti.getModel();
        try {
            mtk.izbaciKlijenta(tblKlijenti.getSelectedRow());
            JOptionPane.showMessageDialog(rootPane, "Klijent je izbacen.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }        
    }//GEN-LAST:event_btnIzbaciKlijentaActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        
        try {
            btnIzbaciKlijenta.setEnabled(true);
            btnIzbaciKlijenta.setVisible(true);
            btnPokreniServer.setEnabled(false);
            btnZaustaviServer.setEnabled(true);
            panelTblKlijenti.setVisible(true);
            Util.getInstance().setUrl(txtUrl.getText().trim());
            Util.getInstance().setPassword(String.valueOf(txtPassword.getPassword()).trim());
            Util.getInstance().setUsername(txtUsername.getText().trim());
            txtUrl.setEnabled(false);
            txtPassword.setEnabled(false);
            txtUsername.setEnabled(false);
            server = new ThreadServer(9009, (ModelTblKlijenti) tblKlijenti.getModel());
            server.start();
            JOptionPane.showMessageDialog(this, "Server je pokrenut.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Greska: Nije moguce pokrenuti server.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } 
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviServerActionPerformed
        
        try {
            btnPokreniServer.setEnabled(true);
            btnZaustaviServer.setEnabled(false);
            txtUrl.setEnabled(true);
            txtPassword.setEnabled(true);
            txtUsername.setEnabled(true);
            btnIzbaciKlijenta.setEnabled(false);
            server.interrupt();
            ((ThreadServer) server).stopThread();
            ModelTblKlijenti mtk = (ModelTblKlijenti) tblKlijenti.getModel();
            mtk.izbaciSveKlijente();
            mtk.fireTableDataChanged();
            JOptionPane.showMessageDialog(rootPane, "Server zaustavljen.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnZaustaviServerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbaciKlijenta;
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelSveKomponente;
    private javax.swing.JPanel panelTblKlijenti;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        srediTabeluKlijenti();
        srediParametre();
    }

    private void srediTabeluKlijenti() {
        ModelTblKlijenti mtk = new ModelTblKlijenti(Session.getInstance().getKlijenti());
        tblKlijenti.setModel(mtk);
        Session.getInstance().setMtk(mtk);
    }

    private void srediParametre() {
        try {
            txtPassword.setText(Util.getInstance().getPassword());
            txtUsername.setText(Util.getInstance().getUsername());
            txtUrl.setText(Util.getInstance().getUrl());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
}
