/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Konobar;
import domen.Narudzbina;
import domen.StavkaNarudzbine;
import domen.Sto;
import forme.modeli.ModelTblNarudzbine;
import forme.modeli.ModelTblStavkeNarudzbine;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableColumn;
import logic.Kontroler;
import session.Session;

/**
 *
 * @author alekd_000
 */
public class FrmNarudzbinePojedinacno extends javax.swing.JFrame {

    Narudzbina narudzbina;
    Mod mod;
    int ukupno = 0;
    ModelTblNarudzbine mtn;
    
    /**
     * Creates new form FrmNarudzbinaPojedinacno
     */
    public FrmNarudzbinePojedinacno(Mod mod, Narudzbina narudzbina, Konobar konobar, ModelTblNarudzbine mtn) {
        initComponents();
        this.narudzbina = narudzbina;
        this.mod = mod;
        this.mtn = mtn;
        lblBrojNarudzbineVal.setVisible(false);
        lblDatumVal.setVisible(false);
        lblStavkeNarudzbineVal.setVisible(false);
        srediFormu();
        
        if (mod == Mod.NEW) {
            txtUkupnaVrednost.setEnabled(false);
            cbKonobari.setSelectedItem(konobar);
            cbKonobari.setEnabled(false);
            cbStornirana.setSelectedItem(Boolean.FALSE);
            cbStornirana.setEnabled(false);
            txtUkupnaVrednost.setText(ukupno + "");
        } 
        if (mod == Mod.VIEW) {            
            txtBrojNarudzbine.setEnabled(false);
            txtDatum.setEnabled(false);
            txtUkupnaVrednost.setEnabled(false);
            cbKonobari.setEnabled(false);
            cbStolovi.setEnabled(false);
            cbStornirana.setEnabled(false);
            tblStavkeNarudzbine.setEnabled(false);
            btnSacuvajNarudzbinu.setVisible(false);
            btnDodajStavkuNarudzbine.setVisible(false);
            btnObrisiStavkuNarudzbine.setVisible(false);
        }   
        if (mod == Mod.EDIT) {
            txtBrojNarudzbine.setEnabled(false);
            txtUkupnaVrednost.setEnabled(false);
            cbStornirana.setEnabled(false);
            cbKonobari.setEnabled(false);
            txtDatum.setEnabled(false);
        }
        if (mod == Mod.EDIT || mod == Mod.VIEW) {
            txtBrojNarudzbine.setText(narudzbina.getNarudzbinaID() + "");
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy.");
            formatter.withLocale(Locale.ITALY);
            LocalDate datumLocalDate = narudzbina.getDatum();
            String datum = datumLocalDate.format(formatter);
            txtDatum.setText(datum + "");
            txtUkupnaVrednost.setText(narudzbina.getUkupnaVrednost() + "");
            cbKonobari.setSelectedItem(narudzbina.getKonobar());
            cbStolovi.setSelectedItem(narudzbina.getSto());
            cbStornirana.setSelectedItem(narudzbina.isStornirana());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNarudzbina = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbStolovi = new javax.swing.JComboBox();
        cbKonobari = new javax.swing.JComboBox();
        txtBrojNarudzbine = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        txtUkupnaVrednost = new javax.swing.JTextField();
        cbStornirana = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeNarudzbine = new javax.swing.JTable();
        lblBrojNarudzbineVal = new javax.swing.JLabel();
        lblDatumVal = new javax.swing.JLabel();
        btnDodajStavkuNarudzbine = new javax.swing.JButton();
        btnObrisiStavkuNarudzbine = new javax.swing.JButton();
        btnSacuvajNarudzbinu = new javax.swing.JButton();
        lblStavkeNarudzbineVal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Narudžbina");

        panelNarudzbina.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o narudžbini"));
        panelNarudzbina.setToolTipText("");

        jLabel1.setText("Broj narudžbine");

        jLabel2.setText("Datum");

        jLabel3.setText("Ukupna vrednost");

        jLabel4.setText("Stornirana");

        jLabel5.setText("Konobar");

        jLabel6.setText("Sto");

        jLabel7.setText("Stavke narudžbine");

        tblStavkeNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblStavkeNarudzbine);

        lblBrojNarudzbineVal.setForeground(new java.awt.Color(255, 0, 0));
        lblBrojNarudzbineVal.setText("Morate uneti broj narudžbine!");

        lblDatumVal.setForeground(new java.awt.Color(255, 0, 0));
        lblDatumVal.setText("Morate uneti datum! [dd.MM.yyyy.]");

        btnDodajStavkuNarudzbine.setText("+");
        btnDodajStavkuNarudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuNarudzbineActionPerformed(evt);
            }
        });

        btnObrisiStavkuNarudzbine.setText("-");
        btnObrisiStavkuNarudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuNarudzbineActionPerformed(evt);
            }
        });

        btnSacuvajNarudzbinu.setText("Sačuvaj narudžbinu");
        btnSacuvajNarudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajNarudzbinuActionPerformed(evt);
            }
        });

        lblStavkeNarudzbineVal.setForeground(new java.awt.Color(255, 0, 0));
        lblStavkeNarudzbineVal.setText("Morate uneti barem jednu stavku narudžbine! Svaka stavka mora da ima odabrani artikal i kolicinu vecu od 0!");

        javax.swing.GroupLayout panelNarudzbinaLayout = new javax.swing.GroupLayout(panelNarudzbina);
        panelNarudzbina.setLayout(panelNarudzbinaLayout);
        panelNarudzbinaLayout.setHorizontalGroup(
            panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNarudzbinaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNarudzbinaLayout.createSequentialGroup()
                        .addComponent(btnDodajStavkuNarudzbine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiStavkuNarudzbine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNarudzbinaLayout.createSequentialGroup()
                        .addComponent(btnSacuvajNarudzbinu)
                        .addContainerGap())))
            .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                        .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                                .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbStolovi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKonobari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbStornirana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrojNarudzbine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrojNarudzbineVal)
                            .addComponent(lblDatumVal)))
                    .addComponent(jScrollPane1)
                    .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                        .addComponent(lblStavkeNarudzbineVal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelNarudzbinaLayout.setVerticalGroup(
            panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNarudzbinaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNarudzbinaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrojNarudzbine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrojNarudzbineVal))
                        .addGap(18, 18, 18)
                        .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumVal)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbStornirana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cbKonobari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbStolovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNarudzbinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnObrisiStavkuNarudzbine)
                        .addComponent(btnDodajStavkuNarudzbine))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblStavkeNarudzbineVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajNarudzbinu)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNarudzbina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNarudzbina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuNarudzbineActionPerformed
        ModelTblStavkeNarudzbine mtk = (ModelTblStavkeNarudzbine) tblStavkeNarudzbine.getModel();
        mtk.dodajPraznuStavkuNarudzbine();
    }//GEN-LAST:event_btnDodajStavkuNarudzbineActionPerformed

    private void btnObrisiStavkuNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuNarudzbineActionPerformed
        ModelTblStavkeNarudzbine mtk = (ModelTblStavkeNarudzbine) tblStavkeNarudzbine.getModel();
        mtk.obrisiStavku(tblStavkeNarudzbine.getSelectedRow());
    }//GEN-LAST:event_btnObrisiStavkuNarudzbineActionPerformed

    private void btnSacuvajNarudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajNarudzbinuActionPerformed
        if (!validacija()) {
            return;
        }
        narudzbina.setNarudzbinaID(Integer.parseInt(txtBrojNarudzbine.getText()));        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy.");
        formatter.withLocale(Locale.ITALY);
        LocalDate datum = LocalDate.parse(txtDatum.getText(), formatter);
        narudzbina.setDatum(datum);  
        narudzbina.setUkupnaVrednost(Double.parseDouble(txtUkupnaVrednost.getText()));
        narudzbina.setKonobar((Konobar) cbKonobari.getSelectedItem());
        narudzbina.setStornirana((boolean) cbStornirana.getSelectedItem());
        narudzbina.setSto((Sto) cbStolovi.getSelectedItem());
        for (StavkaNarudzbine stavka : narudzbina.getStavkeNarudzbine()) {
            stavka.setNarudzbina(narudzbina);
        }
        if (mod == Mod.NEW) {
            try {
                Kontroler.getInstance().kreirajNarudzbinu(narudzbina);
                JOptionPane.showMessageDialog(rootPane, "Narudzbina uspesno kreirana.");
                mtn.dodajNarudzbinu(narudzbina);
            } catch (Exception ex) {
                Logger.getLogger(FrmNarudzbinePojedinacno.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        
        if (mod == Mod.EDIT) {
            ModelTblStavkeNarudzbine mtsn = (ModelTblStavkeNarudzbine) tblStavkeNarudzbine.getModel();
            mtsn.izmeniNarudzbinu();
            try {
                Narudzbina nar = Kontroler.getInstance().izmeniNarudzbinu(narudzbina);
                JOptionPane.showMessageDialog(rootPane, "Narudzbina uspesno izmenjena.");
            } catch (Exception ex) {
                Logger.getLogger(FrmNarudzbinePojedinacno.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        dispose();        
        
    }//GEN-LAST:event_btnSacuvajNarudzbinuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavkuNarudzbine;
    private javax.swing.JButton btnObrisiStavkuNarudzbine;
    private javax.swing.JButton btnSacuvajNarudzbinu;
    private javax.swing.JComboBox cbKonobari;
    private javax.swing.JComboBox cbStolovi;
    private javax.swing.JComboBox cbStornirana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojNarudzbineVal;
    private javax.swing.JLabel lblDatumVal;
    private javax.swing.JLabel lblStavkeNarudzbineVal;
    private javax.swing.JPanel panelNarudzbina;
    private javax.swing.JTable tblStavkeNarudzbine;
    private javax.swing.JTextField txtBrojNarudzbine;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtUkupnaVrednost;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        srediCBStornirana();
        srediCBKonobari();
        srediCBStolovi();
        srediTabelu();
    }


    private void srediCBStornirana() {
        cbStornirana.addItem(true);
        cbStornirana.addItem(false);
    }

    private void srediCBKonobari() {
        try {
            List<Konobar> konobari = Kontroler.getInstance().vratiKonobare();
            for (Konobar konobar : konobari) {
                cbKonobari.addItem(konobar);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmNarudzbinePojedinacno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediCBStolovi() {
        try {
            List<Sto> stolovi = Kontroler.getInstance().vratiStolove();
            for (Sto sto : stolovi) {
                cbStolovi.addItem(sto);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmNarudzbinePojedinacno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediTabelu() {
        
        ModelTblStavkeNarudzbine mtsn = new ModelTblStavkeNarudzbine(narudzbina);
        tblStavkeNarudzbine.setModel(mtsn);
        
        TableColumn tableColumnArtikli = tblStavkeNarudzbine.getColumnModel().getColumn(1);    
        try {
            JComboBox comboBoxArtikli = new JComboBox(new DefaultComboBoxModel(Kontroler.getInstance().vratiArtikle().toArray()));
            tableColumnArtikli.setCellEditor(new DefaultCellEditor(comboBoxArtikli));
            tblStavkeNarudzbine.getModel().addTableModelListener(new TableModelListener() {
                @Override
                public void tableChanged(TableModelEvent e) {
                    txtUkupnaVrednost.setText(narudzbina.getUkupnaVrednost()+ "");
                }
            });
            
        } catch (Exception ex) {
            Logger.getLogger(FrmNarudzbinePojedinacno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean validacija() {
        boolean validator = true;
        String brojNarudzbine = txtBrojNarudzbine.getText();
        try {
            int brojNarudzbineIntTip = Integer.parseInt(brojNarudzbine);
            if (brojNarudzbineIntTip <= 0) {
                throw new NumberFormatException();
            }
            lblBrojNarudzbineVal.setVisible(false);
        } catch (NumberFormatException ex) {
            validator = false;
            lblBrojNarudzbineVal.setVisible(true);
        }
        String datumString = txtDatum.getText();
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy.");
            formatter.withLocale(Locale.ITALY);
            LocalDate datum = LocalDate.parse(datumString, formatter);
            lblDatumVal.setVisible(false);
        } catch (Exception ex) {
            validator = false;
            lblDatumVal.setVisible(true);
        }
        if (narudzbina.getStavkeNarudzbine().size() < 1) {
            validator = false;
        }
        lblStavkeNarudzbineVal.setVisible(narudzbina.getStavkeNarudzbine().size() < 1);
        
        if (!narudzbina.getStavkeNarudzbine().isEmpty() && 
                (narudzbina.getStavkeNarudzbine().get(narudzbina.getStavkeNarudzbine().size() - 1).getArtikal() == null ||
                narudzbina.getStavkeNarudzbine().get(narudzbina.getStavkeNarudzbine().size() - 1).getKolicina() <= 0)) {
            validator = false;
        }
        
        lblStavkeNarudzbineVal.setVisible(!narudzbina.getStavkeNarudzbine().isEmpty() && (narudzbina.getStavkeNarudzbine().get(narudzbina.getStavkeNarudzbine().size() - 1).getArtikal()== null || narudzbina.getStavkeNarudzbine().get(0).getKolicina() <= 0));
        return validator;
    }

}
